global:
    seperator: ";"
    name: sc
    source : "data/sc/School_census_2007.rar"

    output : "/tmp/sc"

    web_paths: {
        "data/sc": "http://media.mit.edu/~jspeiser/data/School_census_2007.rar"
    }

    type:
        School_ID : "str"
        Municipality: "str"
        Year: "int"

    rename:
        Enroll_ID: "enrolled"
        Studant_ID: "students"

    agg:
        enrolled: "nunique"
        students: "nunique"

tables:
    ybs:
        pk: ["Year", "Municipality", "School_ID"]
